### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by ebjones011** [dl00/speedrun-browser-android#2]
**Describe the problem**
Hi,i've been using your Speedrun.com app for awhile now,and i just discovered a problem with the app. When i open the App and the Popular section pops up,no games show up on screen. I've checked the other options as well,i've even searched for a game,but nothing pops up. I've tried uninstalling and re-installing the app,but it didn't fix the problem. I have 3 to 4 bars of WIFI,so it should be working just fine,but it isn't.  My Phone Model is LG K40. My Android version is 9.0. Here are some Screenshots i took: 
![Screenshot_20201016-134225](https://user-images.githubusercontent.com/72993770/96293129-46228a80-0fb8-11eb-90d0-2cb8180eb426.png)
![Screenshot_20201016-134300](https://user-images.githubusercontent.com/72993770/96293154-4f135c00-0fb8-11eb-83b8-14d8e267bb9d.png)

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3A XL]
 - OS: [e.g. Android 10 (look in "About Phone")]

**Additional context**

**Comment by dbeal-eth** [comment]
fixed, server was jammed. thanks for reporting!
