### ISSUE TITLE
All-Time Longest Record Holders shows some wrong data

### ISSUE THREAD

**Issue by Avasam** [dl00/speedrun-browser-android#3]
**Describe the problem**
In the game "Pitfall: The Lost Expedition" it says I've had the 100% WR for over 300 days, while in fact I had it for less than 24h

**To Reproduce**
1. Search for Pitfall The Lost Expedition
2. Go under 100%
3. Go to stats

**Expected behavior**
I expected the number by "Avasam" to be more or less 1 day.

**Screenshots**
![Screenshot_20201203-155023](https://user-images.githubusercontent.com/1350584/101087179-dbd1a380-357f-11eb-9248-2176aaafbf89.png)

Another example from 100% PC. This number does not make sense, it should be ~26 days:
![Screenshot_20201203-160500](https://user-images.githubusercontent.com/1350584/101088463-c52c4c00-3581-11eb-82e4-d68c3cd4c977.png)
![Screenshot_20201203-160419](https://user-images.githubusercontent.com/1350584/101088479-ca899680-3581-11eb-8250-2ebcc3ab317f.png)

**Smartphone (please complete the following information):**
 - Device: Motorolla G⁵
 - OS: Android 8.1.0

**Additional context**

**Comment by dl00** [comment]
Thanks for this info. It appears that the date calculation is indeed incorrect. It is recording the date of the prior record holder as belonging to you. This should be fixed within a few days. :+1: 

As for the times discrepency you seem to be pointing out with the 100% PC category, are those times calculated ingame? Most likely what is happening is that the app is incorrectly using RTA somehow when it should be using ingame time. But I will have to check. :confused: 

In the future, please submit problems as separate issues would help me out.

**Comment by Avasam** [comment]
I didn't think those were two separate issues. I would've created two different bugs for sure otherwise!
Would you like me to split it into a different issue so you can track it separately?

Times are calculated RTA.

**Comment by dl00** [comment]
this error should have been fixed as of last night's server release. Please reopen if you notice this to continue to be incorrect.

Thanks for reporting, really helps the project out!
