### ISSUE TITLE
Going back from a game's stats brings back to main menu

### ISSUE THREAD

**Issue by Avasam** [dl00/speedrun-browser-android#4]
**Describe the problem**
Going back from stats brings me back to the main page. Forcing me to search for the game again.

**To Reproduce**
1. From the main menu, search a game (I searched for "Pitfall") 
2. Tap on the game to navigate to it
3. Tap on either "View Rules/Stats" at the bottom, or the stats icon button at the top right.
4. Go back by using the arrow at the top left, or the phone's back button

**Expected behavior**
At step 4, pressing the back button should've shown me the game I was looking at.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto G⁵
 - OS: Android 8.1.0

**Additional context**

**Comment by dl00** [comment]
Thanks, this is indeed bad navigation. I will check in on that and hopefully come up with an effective solution on the upcoming release this weekend.

**Comment by dl00** [comment]
@Avasam thanks for your report. this should be fixed in the latest version of the app (v1.18.x). Let me know if you notice anything else!
