### ISSUE TITLE
Long time to update the app.

### ISSUE THREAD

**Issue by Setya775** [dl00/speedrun-browser-android#6]
it takes a long time to update the app, for example, I changed my name from "NumTenhoNome" to "Setya" about 2 weeks ago, but, so far in the app it's like NumTenhoNome ... same thing with runs and etc, solve this then man, boring fuck

![Screenshot_2021-01-07-16-53-45-318_com android chrome](https://user-images.githubusercontent.com/77124064/103938513-1becee80-5109-11eb-9e28-4d292422f324.jpg)

![Screenshot_2021-01-07-16-53-59-350_danb speedrunbrowser](https://user-images.githubusercontent.com/77124064/103938509-1a232b00-5109-11eb-87b8-562d5db1ed7e.jpg)

**Comment by dl00** [comment]
Thanks for your report! Can you let me know exactly when you updated your username? speedrun.com recently "temporarily" blocked pulling of runs from its API https://www.speedrun.com/the_site/thread/hdsiy so if you changed your username within that period, it is possible your name update has not been able to be processed. Nornally this data is loaded and updated by downloading run data.

**Comment by Setya775** [comment]
hmm ... i don't remember right i'll try to find it because i don't even
remember but i'll try to find it and i'll answer you as soon as possible,
by the way, thanks for the quick answer :)

Em qui, 7 de jan de 2021 5:00 PM, Daniel Beal <notifications@github.com>
escreveu:

**Comment by Setya775** [comment]
Hi! I tried to search, but, I didn't find a right date, since the site
speedrun.com doesn't send an email when you change the username, and on the
site they don't speak the last time you changed the username, the only clue
of the date, is that on the website it says that I can change my username
in 51 days, so if you do a calculation it will have the right date, but in
general it's about 1 and a half weeks, but the problem is not only with the
username , but yes also with the runs, for example, currently I have 2
pending runs of mario kart 7, but in the app he says that he has no pending
runs, and yes he does ... so, I expect an answer; 3

Em qui, 7 de jan de 2021 5:04 PM, num tenho nome <
pinheiroalcantaraleonardo@gmail.com> escreveu:

**Comment by dl00** [comment]
SRC has opened up their API again, and I have verified that leaderboards on the app have stabilized.

Please reopen if you notice any further issues!
